module.exports = {
	"foodSections" : {
		12:"BOUL PAT TRAD",
		10:"FROMAGE TRAD",
		38:"SURGELES",
		28:"SAURISSERIE",
		30:"CREMERIE LS",
		22:"BOUCHERIE FRAIS EMB.",
		32:"PAIN PAT LS INDUS",
		20:"BOUCHERIE LS",
		34:"FRUITS ET LEGUMES",
		26:"CHARCUTERIE TRAITEUR LS",
		24:"VOLAILLE LS",
		2:"BOUCHERIE / VOLAILLE TRAD",
		46:"LIQUIDES",
		4:"CHARCUTERIE TRAD",
		6:"TRAITEUR TRAD",
		8:"PRODUITS DE LA MER TRAD",
		40:"EPICERIE SUCREE",
		42:"EPICERIE SALEE"
	},
	"otherSections" : {
		48:"D.P.H.", // Droguerie, Parfumerie, Hygiène
		70:"NON COMMERCIALE",
		66:"PRESTATION DE SERVICE",
		50:"TEXTILE",
		44:"ALIMENTATION POUR ANIMAUX",
		60:"BAZAR LEGER",
		36:"FLEURS ET PLANTES",
		88:"BOUTIQUE SERVICES",
		64:"PRODUITS CULTURELS",
		80:"BOUTIQUE STATION",
		82:"BOUTIQUE PRESSE",
		62:"BAZAR TECHNIQUE"
	}
};
